controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    addPatient:
       path: /patient/add
       controller: App\controller\PatientController::addPatient
       methods: [GET, POST]
